version: "3.9"
services:
  postgres:
    container_name: postgres-container
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=duff
      - PGDATA=/data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
