version: "3"
services:
  postgres:
    container_name: postgres-container
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=duff
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"
  api:
    container_name: api-container
    build: .
    image: duff
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DATABASE=duff
      - DB_PORT=5432
      - APP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
